config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do

      resources :labels do
        collection do
          get :available
        end 
        member do
          get :select
          get :remove
        end
      end

      resources :links do
        collection do
          get :available
        end 
        member do
          get :select
          get :remove
        end
      end

    end

    resources :labels do
      post :update_positions, :on => :collection
    end
    resources :links do
      post :update_positions, :on => :collection
    end
  end
end 

app/controllers/spree/admin/links_controller.rb
module Spree
  module Admin
    class LinksController < Spree::Admin::BaseController

      def index 
        @links = Spree::ProductLink.page(params[:page])
      end

      def new
        @link = Spree::ProductLink.new
      end

      def edit
        @link = Spree::ProductLink.find(params[:id])
      end

      def create 
        @link = Spree::ProductLink.new(params[:product_link])
        if @link.save
          redirect_to spree.admin_links_path, :notice => 'DONE!'
        else
          render :new
        end
      end

      def update
        @link = Spree::ProductLink.find(params[:id])
        if @link.update_attributes(params[:product_link])
          redirect_to :back, :notice => 'DONE!'
        else
          render :edit
        end
      end

      def destroy
        @link = Spree::ProductLink.find(params[:id])
        @link.destroy
        redirect_to :back, :notice => 'DONE!'
      end

      #  for product
      def available
        @links = Spree::ProductLink.all
        @product = Spree::Product.find_by_permalink!(params[:product_id])
      end

      def select
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @link = Spree::ProductLink.find(params[:id])
        @product.links << @link
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def remove
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @link = Spree::ProductLink.find(params[:id])
        @product.links.delete(@link)
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def update_positions
        params[:positions].each do |id, index|
          Spree::ProductLink.where(:id => id).update_all(:position => index)
        end 

        respond_to do |format|
          format.html { redirect_to admin_links_url() }
          format.js  { render :text => 'Ok' }
        end 
      end 

    end
  end
end

app/helpers/spree/admin/links_helper.rb
module Spree::Admin::LinksHelper
end

app/views/spree/admin/links/_form.html.erb
<%= f.field_container :name do %>
  <%= f.label :name, t(:name) %> <span class="required">*</span><br />
  <%= f.text_field :name %>
  <%= f.error_message_on :name %>
<% end %>

<%= f.field_container :content do %>
  <%= f.label :content, t(:content) %> <span class="required">*</span><br />
  <%= f.text_area :content %>
  <%= f.error_message_on :content %>
<% end %>

app/views/spree/admin/links/available.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
 
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Links' } %>

<ul>
    <% @links.each do |link|%>
    <li>
        <%=check_box_tag :links, link.id, @product.links.exists?(link)%><%=link.name%>
    </li>
    <% end %>
</ul>
<script>
    $(function(){
        $('input[type=checkbox]').on('click',function(){
            url=<%=raw admin_product_links_path(@product).to_json%> + '/' + this.value + ( this.checked ? '/select' : '/remove')
            $.get(url)
        })
    })
</script>

app/views/spree/admin/links/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @link } %>

<%= form_for @link, :url => admin_link_path(@link) do |f| %>
    <fieldset>
        <legend><%= t(:edit_link) %></legend>
        <%= render :partial => 'form', :locals => { :f => f } %>
        <p class="form-buttons" data-hook="buttons">
            <%= button t(:update) %> <%= t(:or) %> <%= link_to t(:cancel), :back %>
        </p>

    </fieldset>
<% end %>

app/views/spree/admin/links/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_ot_link">
      <%= button_link_to t(:new_link), new_admin_link_url, { :icon => 'add', :id => 'new_link'} %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:links) %></h1>

<div id="new_link"></div>

<table class="index sortable" id="listing_links" data-hook>
  <tr data-hook="option_header">
    <th><%= t(:name) %></th>
    <th></th>
  </tr>
  <% @links.each do |link| %>
    <tr id="link_<%= link.id %>" data-hook="option_row">
      <td><span class="handle"></span> <%= link.name %></td>
      <td class="actions">
        <%= link_to t(:edit), edit_admin_link_path( link ), :class => 'admin_edit_link' %>
        &nbsp;
        <%= link_to t(:delete), admin_link_path( link ), :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/links/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @link } %>

<%= form_for @link, :url => admin_links_path do |f| %>
    <fieldset>
        <legend><%= t(:new_link) %></legend>
        <%= render :partial => 'form', :locals => { :f => f } %>
        <p class="form-buttons" data-hook="buttons">
            <%= button t(:create) %> <%= t(:or) %> <%= link_to t(:cancel), :back %>
        </p>

    </fieldset>
<% end %>