config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do

      resources :labels do
        collection do
          get :available
        end 
        member do
          get :select
          get :remove
        end
      end

      resources :links do
        collection do
          get :available
        end 
        member do
          get :select
          get :remove
        end
      end

    end

    resources :labels do
      post :update_positions, :on => :collection
    end
    resources :links do
      post :update_positions, :on => :collection
    end
  end
end 

app/controllers/spree/admin/labels_controller.rb
module Spree
  module Admin
    class LabelsController < Spree::Admin::BaseController

      def index 
        @labels = Spree::ProductLabel.page(params[:page])
      end

      def new
        @label = Spree::ProductLabel.new
      end
      
      def edit
        @label = Spree::ProductLabel.find(params[:id])
      end
      
      def create 
        @label = Spree::ProductLabel.new(params[:product_label])
        if @label.save
          redirect_to spree.admin_labels_path, :notice => 'DONE!'
        else
          render :new
        end
      end

      def update
        @label = Spree::ProductLabel.find(params[:id])
        if @label.update_attributes(params[:product_label])
          redirect_to :back, :notice => 'DONE!'
        else
          render :edit
        end
      end

      def destroy
        @label = Spree::ProductLabel.find(params[:id])
        @label.destroy
        redirect_to :back, :notice => 'DONE!'
      end
      
      #  for product
      def available
        @labels = Spree::ProductLabel.all
        @product = Spree::Product.find_by_permalink!(params[:product_id])
      end

      def select
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @label = Spree::ProductLabel.find(params[:id])
        @product.labels << @label
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def remove
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @label = Spree::ProductLabel.find(params[:id])
        @product.labels.delete(@label)
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def update_positions
        params[:positions].each do |id, index|
          Spree::ProductLabel.where(:id => id).update_all(:position => index)
        end 

        respond_to do |format|
          format.html { redirect_to admin_labels_url() }
          format.js  { render :text => 'Ok' }
        end 
      end 

    end
  end
end

app/helpers/spree/admin/labels_helper.rb
module Spree::Admin::LabelsHelper
end

app/views/spree/admin/labels/available.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
 
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Labels' } %>

<ul>
    <% @labels.each do |label|%>
    <li>
        <%=check_box_tag :labels, label.id, @product.labels.exists?(label)%><%=label.name%>
    </li>
    <% end %>
</ul>
<script>
    $(function(){
        $('input[type=checkbox]').on('click',function(){
            url=<%=raw admin_product_labels_path(@product).to_json%> + '/' + this.value + ( this.checked ? '/select' : '/remove')
            $.get(url)
        })
    })
</script>

app/views/spree/admin/labels/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @label } %>

<%= form_for @label, :url => admin_label_path(@label) do |f| %>
    <fieldset>
        <legend><%= t(:Edit_label) %></legend>
        <%= render :partial => 'form', :locals => { :f => f } %>
        <p class="form-buttons" data-hook="buttons">
            <%= button t(:update) %> <%= t(:or) %> <%= link_to t(:cancel), :back %>
        </p>

    </fieldset>
<% end %>

app/views/spree/admin/labels/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_ot_link">
      <%= button_link_to t(:new_label), new_admin_label_url, { :icon => 'add', :id => 'new_label'} %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:labels) %></h1>

<div id="new_label"></div>

<table class="index sortable" id="listing_labels" data-hook>
  <tr data-hook="option_header">
    <th><%= t(:name) %></th>
    <th></th>
  </tr>
  <% @labels.each do |label| %>
    <tr id="label_<%= label.id %>" data-hook="option_row">
      <td><span class="handle"></span> <%= label.name %></td>
      <td class="actions">
        <%= link_to t(:edit), edit_admin_label_path( label ), :class => 'admin_edit_label' %>
        &nbsp;
        <%= link_to t(:delete), admin_label_path( label ), :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/labels/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @label } %>

<%= form_for @label, :url => admin_labels_path do |f| %>
    <fieldset>
        <legend><%= t(:new_label) %></legend>
        <%= render :partial => 'form', :locals => { :f => f } %>
        <p class="form-buttons" data-hook="buttons">
            <%= button t(:create) %> <%= t(:or) %> <%= link_to t(:cancel), :back %>
        </p>

    </fieldset>
<% end %>