config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do

      resources :labels do
        collection do
          get :available
        end 
        member do
          get :select
          get :remove
        end
      end

      resources :links do
        collection do
          get :available
        end 
        member do
          get :select
          get :remove
        end
      end

    end

    resources :labels do
      post :update_positions, :on => :collection
    end
    resources :links do
      post :update_positions, :on => :collection
    end
  end
end 

app/models/spree/product_additional_instruction.rb
class Spree::ProductAdditionalInstruction < ActiveRecord::Base
  default_scope :order => 'position ASC'

  has_and_belongs_to_many :products, 
                          :class_name => "Spree::Product", 
                          :join_table => "spree_product_additional_instructions_products"
end

app/models/spree/product_label.rb
class Spree::ProductLabel < Spree::ProductAdditionalInstruction
end

app/models/spree/product_link.rb
class Spree::ProductLink < Spree::ProductAdditionalInstruction
end

app/controllers/spree/admin/labels_controller.rb
module Spree
  module Admin
    class LabelsController < Spree::Admin::BaseController

      def index 
        @labels = Spree::ProductLabel.page(params[:page])
      end

      def new
        @label = Spree::ProductLabel.new
      end
      
      def edit
        @label = Spree::ProductLabel.find(params[:id])
      end
      
      def create 
        @label = Spree::ProductLabel.new(params[:product_label])
        if @label.save
          redirect_to spree.admin_labels_path, :notice => 'DONE!'
        else
          render :new
        end
      end

      def update
        @label = Spree::ProductLabel.find(params[:id])
        if @label.update_attributes(params[:product_label])
          redirect_to :back, :notice => 'DONE!'
        else
          render :edit
        end
      end

      def destroy
        @label = Spree::ProductLabel.find(params[:id])
        @label.destroy
        redirect_to :back, :notice => 'DONE!'
      end
      
      #  for product
      def available
        @labels = Spree::ProductLabel.all
        @product = Spree::Product.find_by_permalink!(params[:product_id])
      end

      def select
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @label = Spree::ProductLabel.find(params[:id])
        @product.labels << @label
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def remove
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @label = Spree::ProductLabel.find(params[:id])
        @product.labels.delete(@label)
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def update_positions
        params[:positions].each do |id, index|
          Spree::ProductLabel.where(:id => id).update_all(:position => index)
        end 

        respond_to do |format|
          format.html { redirect_to admin_labels_url() }
          format.js  { render :text => 'Ok' }
        end 
      end 

    end
  end
end

app/controllers/spree/admin/links_controller.rb
module Spree
  module Admin
    class LinksController < Spree::Admin::BaseController

      def index 
        @links = Spree::ProductLink.page(params[:page])
      end

      def new
        @link = Spree::ProductLink.new
      end

      def edit
        @link = Spree::ProductLink.find(params[:id])
      end

      def create 
        @link = Spree::ProductLink.new(params[:product_link])
        if @link.save
          redirect_to spree.admin_links_path, :notice => 'DONE!'
        else
          render :new
        end
      end

      def update
        @link = Spree::ProductLink.find(params[:id])
        if @link.update_attributes(params[:product_link])
          redirect_to :back, :notice => 'DONE!'
        else
          render :edit
        end
      end

      def destroy
        @link = Spree::ProductLink.find(params[:id])
        @link.destroy
        redirect_to :back, :notice => 'DONE!'
      end

      #  for product
      def available
        @links = Spree::ProductLink.all
        @product = Spree::Product.find_by_permalink!(params[:product_id])
      end

      def select
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @link = Spree::ProductLink.find(params[:id])
        @product.links << @link
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def remove
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @link = Spree::ProductLink.find(params[:id])
        @product.links.delete(@link)
        respond_to do |format|
          format.html { redirect_to :back }
          format.js  { render :text => 'Ok' }
        end 
      end

      def update_positions
        params[:positions].each do |id, index|
          Spree::ProductLink.where(:id => id).update_all(:position => index)
        end 

        respond_to do |format|
          format.html { redirect_to admin_links_url() }
          format.js  { render :text => 'Ok' }
        end 
      end 

    end
  end
end

app/helpers/spree/admin/labels_helper.rb
module Spree::Admin::LabelsHelper
end

app/helpers/spree/admin/links_helper.rb
module Spree::Admin::LinksHelper
end

app/helpers/spree/spree_plus_helper.rb
module Spree
  module SpreePlusHelper
    def spreeplus_breadcrumbs(taxon, separator="")
      return "" if current_page?("/") || taxon.nil?
      separator = raw(separator)
      crumbs = [content_tag(:li, link_to(t(:home) , root_path) + separator, :class => 'home')]
      if taxon
        crumbs << content_tag(:li, link_to(t(:products) , products_path) + separator)
        crumbs << taxon.ancestors.collect { |ancestor| content_tag(:li, link_to(ancestor.name , seo_url(ancestor)) + separator) } unless taxon.ancestors.empty?
        crumbs << content_tag(:li, content_tag(:span, taxon.name))
      else
        crumbs << content_tag(:li, content_tag(:span, t(:products)))
      end
      crumb_list = content_tag(:ul, raw(crumbs.flatten.map{|li| li.mb_chars}.join), :class => 'clearfix')
      content_tag(:div,
          content_tag(:div, crumb_list, :class => 'inner'),
          :id => 'breadcrumbs')

    end

    def sidebar_class
      content_for?(:sidebar) ? 'has-sidebar' : ''
    end
  end
end

app/views/spree/shared/_filters.html.erb
<!-- without filter -->

app/views/spree/shared/_head.html.erb
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<title><%= title %></title>
<%== meta_data_tags %>
<%= favicon_link_tag image_path('favicon.ico') %>
<%= stylesheet_link_tag 'store/all', :media => 'screen' %>
<%= csrf_meta_tags %>
<!-- html5shiv http://code.google.com/p/html5shiv/ -->
<!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<%= javascript_include_tag 'store/all'%>
<%= yield :head %>

app/views/spree/shared/_login.html.erb
<%= form_for :user, :url => spree.user_session_path, :html => {:class => "custom-form"} do |f| %>
    <div class="field">
        <%= f.label :email, t(:email), :class => 'desc' %>
        <div class="col">
            <%= f.email_field :email, :size => "30" %>
        </div>
    </div>
    <div class="field">
        <%= f.label :password, t(:password), :class => 'desc' %>
        <div class="col">
            <%= f.password_field :password, :size => "30" %>
        </div>
    </div>
    <div class="field">
        <div class="col remember">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me, t(:remember_me) %>
        </div>
    </div>

    <div class="button-area">
        <%= f.submit t(:log_in), :class => 'submit button-gray' %>
        <%= t(:or) %> <%= link_to t(:create_a_new_account), spree.signup_path %> | <%= link_to t(:forgot_password), spree.new_user_password_path %>
    </div>
<% end %>

app/views/spree/shared/_login_bar.html.erb
<div class="account block">
    <% if current_user %>
        <%= link_to t(:my_account), spree.account_path, :class => 'login' %>
        <%= link_to t(:logout), spree.destroy_user_session_path %>
    <% else %>
        <%= link_to t(:log_in), spree.login_path, :class => "login" %>
    <% end %>
</div>

app/views/spree/shared/_nav_bar.html.erb
<li id="search-bar" data-hook>
  <%= render :partial => 'spree/shared/search' %>
</li>
<% if store_menu? %>
  <%= render :partial => 'spree/shared/store_menu' %>
<% end %>

app/views/spree/shared/_products.html.erb
<%= render :partial => 'spree/shared/products_nav'%>

<div class="bd">
    <%
      variants = products # DIRTY HACK
      paginated_variants = @searcher.variants if params.key?(:keywords)
      paginated_variants ||= variants
    %>
    <% if variants.empty? %>
      <%= t(:no_variants_found) %>
    <% elsif params.key?(:keywords) %>
      <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
    <% end %>
    
    <% if variants.any? %>
        <ul id="products" class="inventory-<%= params[:display] || 'thumb'%> clearfix" data-hook>
      <% variants.each do |variant| %>
        <% if Spree::Config[:show_zero_stock_products] || variant.in_stock %>
            <% variant_params = {} %>
            <% variant.option_values.each{|x| variant_params["option_types[#{x.option_type_id}]"] = x.id} %>
            <li id="variant_<%= variant.id %>" data-hook="variants_list_item">
                <%if params[:display] == 'list'%>
                    <%= link_to ( small_image( variant.first_image_variant || variant.product)),
                        product_path(variant.product, variant_params), :class=>"photo-thumb" %>
                    <div class="list-intro">
                        <h3><%=link_to variant.name,  product_path(variant.product, variant_params) %></h3>
                        <p><%= truncate variant.product.description, :length => 200%></p>
                    </div>
                    <strong class="price"><%= number_to_currency(variant.price)%></strong>
                <% else %>
                    <%= link_to ( small_image( variant.first_image_variant || variant.product) + 
                                 variant.name + 
                                 raw("<strong>#{number_to_currency(variant.price)}</strong>") ),
                                 product_path(variant.product, variant_params) %>
                <% end %>
           </li>
        <% end %>
      <% end %>
    </ul>
    <% end %>
</div>

<% if paginated_variants.respond_to?(:num_pages)
      params.delete(:search)
      params.delete(:taxon)
      %><%= paginate paginated_variants, :theme => 'store' %><% end %>

app/views/spree/shared/_products_nav.html.erb
<div class="hd clearfix">
    <ul class="clearfix">
        <li class="first"><strong><%=I18n.t("sort_by.sort_by")%></strong></li>
        <li class="<%=  !['price.desc', 'available_on.desc'].include?(params[:order_by]) ? 'current' : ''%>"><%= link_to  I18n.t("sort_by.price_asc"), :order_by => 'price.asc'%></li>
        <li class="<%= (params[:order_by] == 'price.desc' )? 'current' : ''%>"><%= link_to I18n.t("sort_by.price_desc"), :order_by => 'price.desc'%></li>
        <li class="last <%= (params[:order_by] == 'available_on.desc' )? 'current' : ''%> "><%= link_to I18n.t('sort_by.available_desc'), :order_by => 'available_on.desc'%></li>
    </ul>
    <div class="switch">
        <%= link_to I18n.t("display.thumb"), {:display => nil}, :class=> 'thumb ' + (params[:display] != 'list'  ? 'current' : '' )%>
        <%= link_to I18n.t("display.list"), {:display => "list"}, :class=> 'list ' + (params[:display] == 'list'  ? 'current' : '')%>
    </div>
</div>

app/views/spree/shared/_search.html.erb
<%= form_tag products_url, :method => :get do %>
  <%= hidden_field_tag :taxon, '' %>
  <%= text_field_tag :keywords, params[:keywords], :class =>"text", :placeholder => t(:search) %>
  <%= submit_tag t(:search), :name => nil, :class => "submit" %>
<% end %>

app/views/spree/shared/_store_footer.html.erb
<footer>
<div class="inner clearfix">
    <address>© 2011 Handlino Inc.</address>
    <ul class="link clearfix">
        <li class="first"><a href="/">關於Shopping Bags</a></li>
        <li><a href="/">聯絡我們</a></li>
    </ul>
</div>
</footer>

app/views/spree/shared/_taxonomies.html.erb
<div id="taxonomies" class="sidebar-item" data-hook>
    <% get_taxonomies.each do |taxonomy| %>
        <div class="category">
            <h3 class='taxonomy-root'><%= t(:shop_by_taxonomy, :taxonomy => taxonomy.name.singularize) %></h3>
            <%= taxons_tree(taxonomy.root, @taxon || (@product && @product.taxons.first), Spree::Config[:max_level_in_taxons_menu] || 1) %>
        </div>
    <% end %>
</div>

app/views/spree/shared/_user_form.html.erb
<div id="password-credentials">
    <div class="field">
        <%= f.label :email, t(:email), :class => 'desc' %>
        <div class="col">
            <%= f.email_field :email, :size => "30" %>
        </div>
    </div>
    <div class="field">
        <%= f.label :password, t(:password), :class => 'desc' %>
        <div class="col">
            <%= f.password_field :password, :size => "30" %>
        </div>
    </div>
    <div class="field">
        <%= f.label :password_confirmation, t(:confirm_password), :class => 'desc' %>
        <div class="col">
            <%= f.password_field :password_confirmation, :size => "30" %>
        </div>
    </div>
</div>

<div data-hook="signup_below_password_fields"></div>